config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'developers#index'

  resources :developers, only: [:show, :index] do
    resources :building_complexes do
      resources :properties do
        resources :floors
      end
    end
  end
end

app/models/building_complex.rb
class BuildingComplex < ActiveRecord::Base

  belongs_to :user
  has_many :properties, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :user_id, presence: true
end

app/controllers/building_complexes_controller.rb
class BuildingComplexesController < ApplicationController
  before_filter :load_developer
  before_filter :load_building_complex, except: [:index, :new, :create]

  def index
    authorize BuildingComplex
    @building_complexes = collection
  end

  def new
    @building_complex = collection.new
    authorize @building_complex
  end

  def create
    @building_complex = collection.new(building_complex_params)
    authorize @building_complex
    if @building_complex.save
      redirect_to developer_building_complexes_url,
                  notice: t('.created', building_complex: @building_complex.name)
    else
      flash.now[:alert] = t('.create_error')
      render :new
    end
  end

  def edit
    authorize @building_complex
  end

  def update
    authorize @building_complex
    if @building_complex.update_attributes(building_complex_params)
      redirect_to developer_building_complexes_url(@developer),
                  notice: t('.updated', building_complex: @building_complex.name)
    else
      flash.now[:alert] = t('.update_error')
      render :edit
    end
  end

  def show
    authorize @building_complex
  end

  def destroy
    authorize @building_complex
    if @building_complex.destroy
      redirect_to developer_building_complexes_url,
                  notice: t('.destroyed')
    else
      redirect_to developer_building_complexes_url,
                  notice: t('.not_destroyed')
    end
  end

  private

  def collection
    BuildingComplex.where(user_id: params[:developer_id])
  end

  def load_developer
    @developer = User.developers.find(params[:developer_id])
  end

  def load_building_complex
    @building_complex = collection.find(params[:id])
  end

  def building_complex_params
    params.require(:building_complex).permit(:name, :description)
  end
end

app/views/building_complexes/_form.haml
= simple_form_for @building_complex, url: url do |f|
  = f.input :name
  = f.input :description
  = f.button :submit

app/views/building_complexes/edit.haml
.sheet_title
  - content_for :page_title, t('.title')

- if BuildingComplexPolicy.new(current_user, @building_complex).destroy?
  = link_to t('.delete'),
            developer_building_complex_path(@developer, @building_complex),
            data: { confirm: t('.confirm_delete') },
            method: :delete
= render 'form', url: developer_building_complex_path(@developer, @building_complex)

app/views/building_complexes/index.haml
.sheet_title
  - content_for :page_title, t('.title', developer: @developer.name)

- if BuildingComplexPolicy.new(current_user, @building_complexes.new).new?
  = link_to t('.create_building_complex'), new_developer_building_complex_path(@developer)

.sheet_content
  - if @building_complexes.present?
    %table
      %thead
        %th= t('.name')
        %th= t('.properties')
      %body
        - @building_complexes.each do |building_complex|
          %tr
            %td
              - if BuildingComplexPolicy.new(current_user, building_complex).edit?
                = link_to building_complex.name,
                          edit_developer_building_complex_path(@developer, building_complex)
              - else
                = link_to building_complex.name,
                          developer_building_complex_path(@developer, building_complex)
            %td
              = link_to t('.show_properties'),
                        developer_building_complex_properties_path(@developer, building_complex)

  - else
    %p= t('.records_not_found')

app/views/building_complexes/new.haml
.sheet_title
  - content_for :page_title, t('.title')

= render 'form', url: developer_building_complexes_path

app/views/building_complexes/show.haml
.sheet_title
  - content_for :page_title, t('.title')

.sheet_content.listing
  .building_complex
    %span.item-title
      = t('.building_complex')
    %span.item-content
      = @building_complex.name
  .developer
    %span.item-title
      = t('.developer')
    %span.item-content
      = @developer.name
  .description
    %span.item-title
      = t('.description')
    %span.item-content
      = @building_complex.description