config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'developers#index'

  resources :developers, only: [:show, :index] do
    resources :building_complexes do
      resources :properties do
        resources :floors
      end
    end
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index
    @developers = collection.joins(:building_complexes)
                            .select('users.*, count(users.id) AS building_complexes_count')
                            .group('users.id')
                            .order('building_complexes_count desc')
  end

  def show
    @developer = collection.find(params[:id])
  end

  private

  def collection
    User.developers
  end
end

app/views/developers/index.haml
.profile_settings
  - content_for :profile_settings, true
.sheet_title
  - content_for :page_title, t('.title')

.sheet_content
  - if @developers.present?
    %table
      %thead
        %th= t('.developer_name')
        %th= t('.building_complexes')
      %body
        - @developers.each do |developer|
          %tr
            %td= link_to developer.name, developer_path(developer)
            %td
              = link_to t('.show_building_complexes', count: developer.building_complexes_count),
                        developer_building_complexes_path(developer)
  - else
    %p= t('.records_not_found')

app/views/developers/show.haml
.sheet_title
  - content_for :page_title, t('.title')

.sheet_content.listing
  .name
    %span.item-title
      = t('.name')
    %span.item-content
      = @developer.name
  .contact_info
    %span.item-title
      = t('.contact_info')
    %span.item-content
      = @developer.email