config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'developers#index'

  resources :developers, only: [:show, :index] do
    resources :building_complexes do
      resources :properties do
        resources :floors
      end
    end
  end
end

app/models/property.rb
class Property < ActiveRecord::Base

  belongs_to :building_complex
  has_many :attachments, as: :imageable, dependent: :destroy
  has_many :floors, dependent: :destroy
  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true, uniqueness: { scope: :building_complex_id }
  validates :building_complex_id, presence: true
  validates :longitude, presence:true, numericality: true
  validates :latitude, presence:true, numericality: true

  acts_as_taggable_on :features
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_filter :load_developer
  before_filter :load_building_complex
  before_filter :load_property, except: [:index, :new, :create]

  def index
    authorize Property
    @properties = collection
  end

  def new
    @property = collection.new
    authorize @property
  end

  def create
    @property = collection.new(property_params)
    authorize @property

    if @property.save
      redirect_to developer_building_complex_properties_url,
                  notice: t('.created', property: @property.name)
    else
      flash.now[:alert] = t('.create_error')
      render :new
    end
  end

  def edit
    authorize @property
  end

  def update
    authorize @property
    if @property.update_attributes(property_params)
      redirect_to developer_building_complex_properties_url,
                  notice: t('.updated', property: @property.name)
    else
      flash.now[:alert] = t('.update_error')
      render :edit
    end
  end

  def show
    authorize @property
  end

  def destroy
    authorize @property
    if @property.destroy
      redirect_to developer_building_complex_properties_url,
                  notice: t('.destroyed')
    else
      redirect_to developer_building_complex_properties_url,
                  notice: t('.not_destroyed')
    end
  end

  private

  def load_property
    @property = collection.find(params[:id])
  end

  def load_developer
    @developer = User.developers.find(params[:developer_id])
  end

  def load_building_complex
    @building_complex = BuildingComplex.where(user_id: params[:developer_id])
                                       .find(params[:building_complex_id])
  end

  def collection
    Property.where(building_complex_id: params[:building_complex_id])
  end

  def property_params
    params.require(:property)
          .permit(:name,
                  :description,
                  :feature_list,
                  :longitude,
                  :latitude,
                  attachments_attributes: [:file, :tempfile, :original_filename, :headers, :_destroy, :id])
  end
end

app/views/properties/_attachment_fields.haml
.nested-fields
  - if f.object.persisted?
    = image_tag f.object.file.url(:medium)
  = f.input :file, as: :file
  = link_to_remove_association t('.remove_property_photo'), f

app/views/properties/_form.haml
= simple_form_for @property, url: url do |f|
  = f.input :name
  = f.input :feature_list
  %h3
    = t('.attachments')
  #attachments
    = f.fields_for :attachments do |attachment|
      = render 'attachment_fields', f: attachment
    .links
      = link_to_add_association t('.add_property_photo'), f, :attachments
  = f.input :description
  = f.input :latitude, as: :string
  = f.input :longitude, as: :string
  = f.button :submit

app/views/properties/edit.haml
.sheet_title
  - content_for :page_title, t('.title')

- if PropertyPolicy.new(current_user, @property).destroy?
  = link_to t('.delete'),
            developer_building_complex_property_path(@developer, @building_complex, @property),
            data: { confirm: t('.confirm_delete') },
            method: :delete

= render 'form', url: developer_building_complex_property_path(@developer, @building_complex, @property)

app/views/properties/index.haml
.sheet_title
  - content_for :page_title,
                t('.title', developer: @developer.name, building_complex: @building_complex.name)

- if PropertyPolicy.new(current_user, @properties.new).new?
  = link_to t('.add_property'),
            new_developer_building_complex_property_path(@developer, @building_complex)
.sheet_content
  - if @properties.present?
    %table
      %thead
        %th= t('.name')
        %th= t('.floors')
      %body
        - @properties.each do |property|
          %tr
            %td
              - if PropertyPolicy.new(current_user, property).edit?
                = link_to property.name,
                        edit_developer_building_complex_property_path(@developer, @building_complex, property)
              - else
                = link_to property.name,
                          developer_building_complex_property_path(@developer, @building_complex, property)
            %td
              = link_to t('.show_floors'),
                        developer_building_complex_property_floors_path(@developer, @building_complex, property)

  - else
    %p= t('.records_not_found')

app/views/properties/new.haml
.sheet_title
  - content_for :page_title, t('.title')

= render 'form', url: developer_building_complex_properties_path

app/views/properties/show.haml
.sheet_title
  - content_for :page_title, t('.title')

.sheet_content.listing
  .name
    %span.item-title
      = t('.name')
    %span.item-content
      = @property.name
  .building_complex
    %span.item-title
      = t('.building_complex')
    %span.item-content
      = @building_complex.name
  .developer
    %span.item-title
      = t('.developer')
    %span.item-content
      = @developer.name
  .description
    %span.item-title
      = t('.description')
    %span.item-content
      = @property.description
  .longitude
    %span.item-title
      = t('.longitude')
    %span.item-content
      = @property.longitude
  .latitude
    %span.item-title
      = t('.latitude')
    %span.item-content
      = @property.latitude

#maps

- @property.attachments.each do |attachment|
  = image_tag attachment.file.url(:medium)