config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'developers#index'

  resources :developers, only: [:show, :index] do
    resources :building_complexes do
      resources :properties do
        resources :floors
      end
    end
  end
end

app/models/floor.rb
class Floor < ActiveRecord::Base
  belongs_to :property
  has_many :attachments, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank

  validates :start_from, numericality: { only_integer: true, greater_than: 0 }
  validates :end_to, numericality: { only_integer: true, greater_than_or_equal_to: :start_from }
  validates :property_id, :start_from, :end_to, presence: true
  validate :property_overlap_ranges


  scope :property_floors, -> (value) { where(property_id: value) }

  def range
    start_from..end_to
  end

  private

  def property_overlap_ranges
    Floor.where.not(id: id).property_floors(property_id).each do |existing_floor|
      if existing_floor.range.overlaps?(range)
        errors[:base] << "New range overlaps existing range for property"
      end
    end
  end
end

app/controllers/floors_controller.rb
class FloorsController < ApplicationController
  before_filter :load_developer
  before_filter :load_building_complex
  before_filter :load_property
  before_filter :load_floor, except: [:index, :new, :create]

  def index
    authorize Property
    @floors = collection
  end

  def new
    @floor = collection.new
    authorize @floor
  end

  def create
    @floor = collection.new(floor_params)
    authorize @floor

    if @floor.save
      redirect_to developer_building_complex_property_floors_url,
                  notice: t('.created', floor: @floor.range)
    else
      flash.now[:alert] = t('.create_error')
      render :new
    end
  end

  def edit
    authorize @floor
  end

  def update
    authorize @floor
    if @floor.update_attributes(floor_params)
      redirect_to developer_building_complex_property_floors_url,
                  notice: t('.updated', floor: @floor.range)
    else
      flash.now[:alert] = t('.update_error')
      render :edit
    end
  end

  def show
    authorize @floor
  end

  def destroy
    authorize @floor
    if @floor.destroy
      redirect_to developer_building_complex_property_floors_url,
                  notice: t('.destroyed')
    else
      redirect_to developer_building_complex_property_floors_url,
                  notice: t('.not_destroyed')
    end
  end

  private

  def load_floor
    @floor = collection.find(params[:id])
  end

  def load_developer
    @developer = User.developers.find(params[:developer_id])
  end

  def load_building_complex
    @building_complex = BuildingComplex.where(user_id: params[:developer_id])
                                       .find(params[:building_complex_id])
  end

  def load_property
    @property = Property.find(params[:property_id])
  end

  def collection
    Floor.where(property_id: params[:property_id])
  end

  def floor_params
    params.require(:floor)
          .permit(:description,
                  :start_from,
                  :end_to,
                  attachments_attributes: [:file, :tempfile, :original_filename, :headers, :_destroy, :id])
  end
end

app/views/floors/_attachment_fields.haml
.nested-fields
  - if f.object.persisted?
    = image_tag f.object.file.url(:medium)
  = f.input :file, as: :file
  = link_to_remove_association t('.remove_floor_plan'), f

app/views/floors/_form.haml
= simple_form_for @floor, url: url do |f|
  = f.input :start_from, as: :string
  = f.input :end_to, as: :string
  %h3
    = t('.attachments')
  #attachments
    = f.fields_for :attachments do |attachment|
      = render 'attachment_fields', f: attachment
    .links
      = link_to_add_association t('.add_floor_plan'), f, :attachments
  = f.input :description
  = f.button :submit

app/views/floors/edit.haml
.sheet_title
  - content_for :page_title, t('.title')

- if FloorPolicy.new(current_user, @floor).destroy?
  = link_to t('.delete'),
            developer_building_complex_property_floor_path(@developer, @building_complex, @property, @floor),
            data: { confirm: t('.confirm_delete') },
            method: :delete

= render 'form', url: developer_building_complex_property_floor_path(@developer, @building_complex, @property, @floor)

app/views/floors/index.haml
.sheet_title
  - content_for :page_title,
                t('.title',
                  developer: @developer.name,
                  building_complex: @building_complex.name,
                  property: @property.name)

- if FloorPolicy.new(current_user, @floors.new).new?
  = link_to t('.add_floor'),
            new_developer_building_complex_property_floor_path(@developer, @building_complex, @property)
.sheet_content
  - if @floors.present?
    %table
      %thead
        %th= t('.floor_range')
      %body
        - @floors.each do |floor|
          %tr
            %td
              - if FloorPolicy.new(current_user, floor).edit?
                = link_to floor.range,
                        edit_developer_building_complex_property_floor_path(@developer, @building_complex, @property, floor)
              - else
                = link_to floor.range,
                          developer_building_complex_property_floor_path(@developer, @building_complex, @property, floo)

  - else
    %p= t('.records_not_found')

app/views/floors/new.haml
.sheet_title
  - content_for :page_title, t('.title')

= render 'form', url: developer_building_complex_property_floors_path

app/views/floors/show.haml
.sheet_title
  - content_for :page_title, t('.title')

.sheet_content.listing
  .name
    %span.item-title
      = t('.range')
    %span.item-content
      = @floor.range
  .property
    %span.item-title
      = t('.property')
    %span.item-content
      = @property.name
  .building_complex
    %span.item-title
      = t('.building_complex')
    %span.item-content
      = @building_complex.name
  .developer
    %span.item-title
      = t('.developer')
    %span.item-content
      = @developer.name
  .description
    %span.item-title
      = t('.description')
    %span.item-content
      = @floor.description

- @floor.attachments.each do |attachment|
  = image_tag attachment.file.url(:medium)